set_project("flux")
set_version("0.1.0")
set_license("MIT")
set_languages("cxx20")
set_encodings("utf-8")

add_rules("mode.debug", "mode.release")
add_requires("entt", "pugixml", "spdlog", "magic_enum", "catch2")

target("flux-lib")
    set_kind("static")
    add_includedirs("src", {public = true})
    add_packages("entt", "pugixml", "spdlog", "magic_enum")
    add_files("src/*.cpp|main.cpp")

target("flux")
    set_kind("binary")
    set_rundir(".")
    add_deps("flux-lib")
    add_packages("spdlog")
    add_files("src/main.cpp")

target("test")
    set_kind("binary")
    set_rundir(".")
    add_deps("flux-lib")
    add_includedirs("src")
    add_packages("entt", "pugixml", "spdlog", "magic_enum", "catch2")
    add_files("tests/*.cpp")
